#The script will take information from the "pool" column (second column), to separate the OTU table into subtables (1 subtable per pool).
setwd("/home/laur/Schreibtisch/NC_filtering_complex_OTU_table/")

#First remove the top left field "#OTU_ID" before reading in.
#Then, read in otu table.
data <- read.table("otu_table_example.csv", sep="\t", header=T, row.names = 1)
head(data)

#Read in the tsv table, which was generated by user input to the site.
tsv <- read.table("example_table.tsv", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
head(tsv)

#Create subtables, one for each pool number (in second column)
pool1names <- tsv[tsv$V2==1 , 1]
pool1names <- gsub("-",".",pool1names)

s1 <- data[ , pool1names]

pool2names <- tsv[tsv$V2==2, 1]
pool2names <- gsub("-",".",pool2names)
s2 <- data[ , pool2names]

pool3names <- tsv[tsv$V2==3, 1]
pool3names <- gsub("-",".",pool3names)
s3 <- data[ , pool3names]

write.table(s1, file="subtable1.csv", sep="\t", quote=F, col.names = NA, append = FALSE)
write.table(s2, file="subtable2.csv", sep="\t", quote=F, col.names = NA)
write.table(s3, file="subtable3.csv", sep="\t", quote=F, col.names = NA)
