#The script will take information from the "pool" column (second column), to separate the OTU table into subtables (1 subtable per pool).
#setwd("/home/laur/Desktop/NC_complex_otu_tables/")

#Top left field "#OTU_ID" has been removed already.
#Then, read in otu table.
data <- read.table("otu_table_example.csv", sep="\t", header=T, row.names = 1)
head(data)

#Read in the tsv table, which was generated by user input to the site.
tsv <- read.table("example_table.tsv", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
head(tsv)

num_pools <- max(tsv$V2)

#Create subtables, one for each pool number (in second column)
for(i in 1:num_pools){
  poolnames <- tsv[tsv$V2==i, 1]
  poolnames <- gsub("-",".",poolnames)
  st <- data[ ,poolnames]
  myfile <- paste0("subtable", i, ".csv")
  write.table(st, file=myfile, sep="\t", quote=F, col.names = NA, append = FALSE)
}
